### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by dan326326** [eashanadhikarla/image-manipulation-detection#3]
hello,  i excute  datedset.py  but get an error as  follow, can you help me?  thank  you!
 
FileNotFoundError: [Errno 2] No such file or directory: './dataset/coco_synthetic/train_filter.txt'

**Comment by eashanadhikarla** [comment]
Sure, the error is because it cannot find the synthetic version of COCO dataset. You can download the dataset from here: https://github.com/pengzhou1108/RGB-N
